module.exports = {
  component: 'list',
  title: 'Gear List',
  list: [
    '2017 iMac Pro (OS Catalina, 3.2 GHz 8-Core Intel Xeon W, 128 GB RAM, Radeon Pro Vega 56 8 GB)',
    'Antelope Audio Discrete 8 SC Thunderbolt Interface',
    'Focusrite ISA One Preamp',
    'Neve 500 Series Rack',
    'A-Designs P-1 Preamps',
    'Empirical Labs DerrEsser',
    'SSL 611EQ',
    'API 527 Compressor',
    'Tree Audio Optical Compressor',
    'Kemper Profiler',
    'Black Lion Audio PG-1 Power Conditioners',
    'Drawmer CMC3 Monitor Controller',
    'ATC SCM20ASL Speakers',
    'Kali Audio LP-6 Speakers',
    'Auratone Mixcube Speakers (With BetterMaker Amp)',
    'Slate Raven MTi',
    'Pro Tools Ultimate 2021.3',
    'Audio Design Desk',
    'Plugins - Waves Audio, Plugin Alliance, Slate Digital, Izotope, Fab Filter, Sound Toys, Softube, Antelope Audio, WavesFactory, Valhalla DSP,  Avid, Krotos, and many more.',
    'Virtual Instruments - Native Instruments, Spitfire Audio, Sonic Academy, Brainworx',
  ],
};
